language: python
node_js: "9"

cache:
  - pip
  - yarn


env:
  global:
    - DISPLAY=':99.0'
    - YARN_VERSION='0.24.5'
    - MC_COMMIT='a1abfeb6a79a' # https://hg.mozilla.org/mozilla-central/shortlog

notifications:
  slack:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - autoconf2.13
      - sshpass
      - p7zip-full
  artifacts:
    paths:
      - $HOME/firefox/mochitest.log

install:
  - pip install --upgrade pip
  - pip install -U mercurial
  - . $HOME/.nvm/nvm.sh; nvm install 9; nvm use 9;
  - ./bin/ci/install-yarn
  - ./bin/ci/clone-gecko.sh
  - du -sh firefox
  - yarn

before_script:
  - ./bin/ci/build-firefox.sh
  - sh -e /etc/init.d/xvfb start

script:
  - node --version
  - du -sh firefox
  - node ./bin/copy-assets.js --mc ./firefox
  - node ./bin/copy-modules.js --mc ./firefox
  - ./bin/ci/build-firefox.sh
  - node ./bin/ci/check-file-sizes.js
  - cd firefox; ./mach mochitest --headless devtools/client/debugger/new
